### ISSUE TITLE
proposal is nog onvoldoende

### ISSUE THREAD

**Issue by stgm** [linomiltenburg/Project#1]
Neem even contact op

**Comment by linomiltenburg** [comment]
Beste Martijn,

Dat kan goed kunnen. Ik heb gister te lang zitten malen wat nou wilde.

Wat ontbrak er nog aan?

Groet,

Lino

Op 5 jan. 2016 om 10:21 heeft Martijn Stegeman <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Neem even contact op
